---
##@file
##
## @brief Example (ansible) YAML
##
##    There is no support for yaml so all style elements should be created.
##
## @version 1.0
##
## @author Arco van Geest <d.a.c.vangeest@tudelft.nl>
##
## @date 20190909 first version
##


##
## Hello world playbook 
## ====================
## This playbook is used to show the use of doxygen\n
## linebreaks are ignored unless \\n is used
##
- name: "Hello world playbook"
  become: false
  hosts: localhost
  ## tasks
  ## -----
  tasks:
    ## ### Show hello world ###
    ## - show hello
    - name: "hello word"
      debug:
        # this message is not shown in documentation
        msg: "Hello world"
    ## - show hello2
    - name: "hello word2"
      debug:
        # this message is not shown in documentation
        msg: "Hello2"
##
